# Generated by Django 3.0 on 2019-12-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('unique_squirrel_ID', models.CharField(max_length=50, unique=True)),
                ('shift', models.CharField(choices=[('pm', 'PM'), ('am', 'AM'), ('other', 'Other')], default='other', max_length=5)),
                ('date', models.DateField(help_text='Date')),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('unknown', 'Unknown or Blank')], default='unknown', max_length=20)),
                ('primary_fur_color', models.CharField(choices=[('black', 'Black'), ('cinamon', 'Cinnamon'), ('gray', 'Gray'), ('other', 'Unknown or Other')], default='other', max_length=20)),
                ('location', models.CharField(choices=[('above ground', 'Above Ground'), ('ground plane', 'Ground Plane'), ('other', 'Other')], default='other', max_length=50)),
                ('specific_location', models.CharField(blank=True, max_length=1000)),
                ('running', models.BooleanField(default=False)),
                ('chasing', models.BooleanField(default=False)),
                ('climbing', models.BooleanField(default=False)),
                ('eating', models.BooleanField(default=False)),
                ('foraging', models.BooleanField(default=False)),
                ('other_activities', models.CharField(blank=True, max_length=1000)),
                ('kuks', models.BooleanField(default=False)),
                ('quaas', models.BooleanField(default=False)),
                ('moans', models.BooleanField(default=False)),
                ('tail_flags', models.BooleanField(default=False)),
                ('tail_twitches', models.BooleanField(default=False)),
                ('approaches', models.BooleanField(default=False)),
                ('indifferent', models.BooleanField(default=False)),
                ('runs_from', models.BooleanField(default=False)),
            ],
        ),
    ]
