# Generated by Django 3.0 on 2019-12-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='unique_squirrel_ID',
            new_name='unique_squirrel_id',
        ),
    ]
