# Generated by Django 3.0 on 2019-12-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191206_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='unique_squirrel_id',
            field=models.CharField(max_length=50),
        ),
    ]
